---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  remote_user: mohak
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "mohak7/sc"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Start Docker service
      service:
        name: docker
        state: started
    - name: Running container 
      shell: docker run -it -d --name sc mohak7/sc
